apiVersion: apps/v1
kind: Deployment

metadata:
  name: flight-price-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: flight-app

  template:
    metadata:
      labels:
        app: flight-app

    spec:
      containers:
      - name: flight-container
        image: flight-price-image
        ports:
        - containerPort: 5000